# Generated by Django 3.1.7 on 2021-05-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190703_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='location',
            field=models.CharField(default='电院大草坪', max_length=256, verbose_name='具体地点'),
        ),
        migrations.AddField(
            model_name='topic',
            name='location_kind',
            field=models.CharField(default='闵行校区', max_length=32, verbose_name='地点类型'),
        ),
        migrations.AddField(
            model_name='topic',
            name='t_contact',
            field=models.CharField(default='QQ:666666', max_length=64, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='topic',
            name='t_number',
            field=models.CharField(default='2', max_length=16, verbose_name='活动人数'),
        ),
        migrations.AddField(
            model_name='topic',
            name='t_time',
            field=models.CharField(default='2021-08-17', max_length=64, verbose_name='活动时间'),
        ),
    ]
